### ISSUE TITLE
Kindle: Numbers in nav not suppressed

### ISSUE THREAD

**Issue by finanzer** [FriendsOfEpub/Blitz#13]
The style 
```
nav[epub|type~="toc"] ol {
  list-style: none !important;
}
```
is not enough to suppress the number of the list at kindle and Calibre viewer. (see screenshots)

![image](https://cloud.githubusercontent.com/assets/10505961/25897982/6adb4828-358a-11e7-926d-1b6a7549f0a5.png)
Calibre Viewer

![image](https://cloud.githubusercontent.com/assets/10505961/25898106/f7af869c-358a-11e7-8f04-6a67d3ed4c6b.png)
Kindle Previewer

I have to give the ol element a class that numbers are suppressed at kindle

`<ol class="toc-list">`

For calibre viewer is an extra rule with the id of the nav element enough. 

The additional css rule to blitz is in my stylesheet now:

```
nav#id ol, ol.toc-list{
  list-style: none !important;
}

```

**Comment by JayPanoz** [comment]
Same problem as #14, namespace is ignored. 

I’ll add a `no-list-type` class in utilities and clarify its usage for nav. 

Once again, I have very little control over how users deal with their toc markup.

**Comment by JayPanoz** [comment]
Closing this as it was addressed a long time ago but please bear in mind [it might not work in the “Look Inside” feature](http://epubsecrets.com/amazon-look-inside-fail.php).
