### ISSUE TITLE
Kindle: nav landmarks not hidden

### ISSUE THREAD

**Issue by finanzer** [FriendsOfEpub/Blitz#14]
The rule 

```
nav[epub|type~="landmarks"],
nav[epub|type~="page-list"] {
  display: none;
}
```
is not enough to hide the landmarks (i think it's with page-list the same but i have no) at kindle (see screenshot)

![image](https://cloud.githubusercontent.com/assets/10505961/25898285/d0a8cb16-358b-11e7-8437-0ba9a30389c2.png)

I have to add the following rule

```
nav#landmarks {
  display: none;
}
```

**Comment by JayPanoz** [comment]
OK thanks I just checked and it seems that Kindle is not taking the `namespace` into account, which is why it fails. 

Alternatively, if you’re using the HTML5 `hidden` attribute, then 

```
[hidden] {
  display: none;
}
```

works too. I’ll add that to the reset since there’s no way I can tell whether user will use an `id` or not.

**Comment by JayPanoz** [comment]
Closing this as it was addressed a long time ago but please bear in mind [it might not work in the “Look Inside” feature](http://epubsecrets.com/amazon-look-inside-fail.php).
