### ISSUE TITLE
Feedback and Support

### ISSUE THREAD

**Issue by kerberosmansour** [FriendsOfEpub/Blitz#24]
Your work is incredible — Thank you. I am on the board of the OWASP Foundation which writes best practices for software security. I was trying to have a project off the ground to be able to publish these books in epub/ebook + physical form. I would very much would like to reach out to you for help — we are an OSS foundation so we have a mutual interest in leveraging open source tools to publish open source content :-)

Here is our page: https://github.com/OWASP/OWASP-Books/ Right now I use a mix of Pandoc & Make — — most of our community writes in MarkDown.

Please reach out when you have a chance!

**Comment by arthurattwell** [comment]
@kerberosmansour I agree about @JayPanoz's wonderful work here :) In addition to Blitz for ebooks, here are three open-source projects that might be of interest, especially if you're aiming to create good-looking physical books:

1. [Editoria](https://editoria.pub/), which is led by the Coko Foundation, which is building an exciting Javascript-based, modular publishing system.
2. [Bookdown](https://bookdown.org/yihui/bookdown/), which uses Rmarkdown to produce books in various formats.
3. The [Electric Book workflow](https://electricbookworks.github.io/electric-book/), which uses Jekyll and markdown to produce books in print, epub, and website forms. (This one is my team's project.)

**Comment by JayPanoz** [comment]
Thanks guys, appreciated. 

@kerberosmansour So you can contact me using the form at the bottom of this page if needed: http://jiminy.chapalpanoz.com/contacter-2/ (sorry in French but "nom" is "name", "email" is "email", "sujet" is "object" and "message" is "message" if that can help).

Actually, thanks for pointing those projects @arthurattwell, as Julien Taquet (who doesn’t have a GitHub account it seems so it’s John_Tax on Twitter), from the Coko Foundation, is exploring a vanilla CSS version of the LESS framework. This is actually something I’ve been willing to do but couldn’t for lack of time.

**Comment by kerberosmansour** [comment]
Our foundation could raise funds for your to build an open source workflow
for our community's books (Mostly in MarkDown).
@JayPanoz <https://github.com/JayPanoz> & @arthurattwell
<https://github.com/arthurattwell>,you can reach me on
sherif(dot)mansour(at)owasp(dot)org
@JayPanoz <https://github.com/JayPanoz>I tried submitting through the form
- it raised an error.
