### ISSUE TITLE
Please tag the 1.4.1 release

### ISSUE THREAD

**Issue by ptmkenny** [FriendsOfEpub/Blitz#42]
Please tag the latest release.

According to the project page, 1.4.1 is the latest release, but there's no tag for 1.4.1-- the latest tag is 1.4.0.

> 1.4.1
> 
>     Fixed padding-left for lists (switched to relative ems) so that markers can’t be cropped
>

**Comment by JayPanoz** [comment]
Woops sorry, thanks for bringing this oversight to my attention. It’s been corrected: https://github.com/FriendsOfEpub/Blitz/releases
