### ISSUE TITLE
[Reset] nav ol

### ISSUE THREAD

**Issue by JayPanoz** [FriendsOfEpub/Blitz#56]
So I’m kinda thinking about modifying the reset and declaring `list-style: none` for every `nav ol`, and not just TOC. 

Per spec, we have this: 

> In the context of this specification, the default display style of list items within nav elements MUST be equivalent to the list-style: none property [CSSSnapshot]. Reading Systems MUST NOT show list item numbering on these lists when presenting the Navigation Document outside of the spine, regardless of their support for CSS. Authors MAY specify alternative list styling using CSS for rendering of the document in the spine. [source](https://www.w3.org/publishing/epub3/epub-packages.html#sec-package-nav-def-model)

And I guess, albeit opinionated, this is the default most people would also use if their navigation document is visible in the EPUB file. Obviously would be overridable. 

A kindle workaround is [already doing that in develop](https://github.com/FriendsOfEpub/Blitz/pull/50/files) so that would remove `!important` and make it global – and not scoped to Kindle.

**Comment by ptmkenny** [comment]
That sounds reasonable to me.

**Comment by JayPanoz** [comment]
Given the Blitz project is under an “End of Life process”, this issue has been frozen, labeled `wontfix`, and won’t be addressed any further. Please check #66 for more details.
