### ISSUE TITLE
How to have asterisms inherit the text color?

### ISSUE THREAD

**Issue by lifepillar** [FriendsOfEpub/Blitz#62]
I don't like much the way asterisms are displayed in night mode (with a white border). I'd rather have them take the text color through a property like `stroke: currentColor`. I was able to achieve that by inlining (a simplified version of) your `asterism.svg`, but I am not sure how well that is supported by ereaders (I have limited testing possibilities). Any recommendations about that? Are there any other ways to achieve what I am asking for? For instance, how about using a simple `<p>* * *</p>` and hiding/removing `<hr/>`?

**Comment by JayPanoz** [comment]
I agree this implementation is a little bit opinionated in the sense it’s the result of trying to use the proper structural element for the task a.k.a. `hr` while managing all ebook-specific constraints e.g. can’t use pseudo-elements, reading modes, resizing… 

So it has all the restrictions of `hr` (void) and `background-image` (isolated styling), combined with the constraints of ebook Reading Systems. 

Quite frankly, given how much time was required to get the existing implementation – research, tests, etc., I would probably use your second option so something like 

```
<div role="separator">* * *</div>
```

The [separator role](https://www.w3.org/WAI/PF/aria/roles#separator) is the one mapped to `hr` so it should work the same with screen readers, although I couldn’t test that so don’t quote me on that. 

In the worst-case scenario, screen readers may read the three asterisks though. Theoretically adding an extra `aria-label` would help e.g. `aria-label="Asterism"` or `aria-label="Interlude"`. At least this is what we’re listing in [Blitz Tricks](https://friendsofepub.github.io/eBookTricks/) for Fake Asterism in the Typo section – so do not hesitate to correct me if you happen to test it with screen readers and it’s wrong.

**Comment by lifepillar** [comment]
Thanks for the detailed feedback! I will opt for the div option then.

**Comment by lifepillar** [comment]
Just one more related question: you suggest to disable user's selection for section breaks, but that's not supported by legacy readers. What's the best way to implement that? I'd do it like this:

```css
div.asterism {
    width: 2.5em;
  margin: 1em auto;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

but, if a legacy reader does not support `user-select`, does that mean that the whole rule (or the whole CSS) would be ignored? Should I use `@supports` then?

**Comment by JayPanoz** [comment]
You could use `@supports` for extra safety but `user-select` should be OK without it and not have any negative impact, as in your example – as a reminder, every time one uses `@supports` it will drop the styles for Reading Apps using Trident (IE11) on Windows. 

As far as I can remember I’ve used it several times in the past w/o any issue in Adobe’s RMSDK; it just ignored the rules. 

Note making this non-selectable is a matter of taste. Maybe you’d prefer those asterisms to be highlighted/copied as they make sense in this context; it’s not clear but the blitz trick is just mimicking how `hr` would typically be handled by the Reading Apps.

**Comment by lifepillar** [comment]
Thanks, super clear!
